# Results

Results will go here

```{r, cache=T, warning=F, message=F, echo=F}
library(raster)
library(sf)
library(tidyverse)
library(cowplot)

theme_custom <- function(...) {
  theme_bw() +
  theme(
    text = element_text(family="Roboto Condensed"),
    axis.text.x = element_text(size=8),
    axis.text.y = element_text(size=8),
    axis.title.x = element_text(size=8),
    axis.title.y = element_text(size=8),
    plot.margin = margin(3,3,1,3, unit="mm"),
    strip.text = element_text(size=8),
    panel.border = element_rect(fill=NA),
    panel.spacing = unit(2, "mm"),
    panel.grid.minor = element_blank(),
    strip.background = element_blank(),
    legend.text = element_text(size=8),
    legend.title = element_text(size=8),
    ...
  )}

scenario_ids = data.frame(ScenarioID=c(128,134,136,138),
                          ScenarioName = c("LULC+Clim", "Clim", "Ref", "LULC"))

```

```{r, flowresults, cache=T, echo=F, warning=F, message=F, fig.width=8, fig.height=3, fig.cap="Net fluxes of carbon in conterminous U.S. forests for the period 2002-2020."}
flowTypes_net = c("Net Primary Productivity", "Net Ecosystem Productivity", "Net Biome Productivity", "Emission: Total")

flows_net = read_csv("data/results/flows_conus.csv") %>%
  left_join(scenario_ids) %>%
  filter(FlowGroupID %in% flowTypes_net)

ggplot(flows_net, aes(x=Timestep, y=Amount/1000000, color=ScenarioName, fill=ScenarioName, shape=ScenarioName)) +
  geom_line() +
  scale_color_brewer(palette="Dark2") +
  geom_point(color="white", size=1.5) +
  scale_fill_brewer(palette="Dark2") +
  scale_shape_manual(values=c("LULC+Clim"=21, "Clim"=22, "LULC"=23, "Ref"=24)) +
  facet_wrap(~FlowGroupID, scales="free_y", ncol=4) +
  theme_custom() +
  labs(x="Year", y=expression(Carbon~flux~(MMT~C~yr^-1)), fill="Scenario", shape="Scenario", color="Scenario") +
  theme(legend.position = "bottom",
        legend.key.width = unit(10, "mm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-10,-10,0,-10))
```

```{r, stockresults, cache=T, echo=F, warning=F, message=F, fig.width=4, fig.height=2.5, fig.cap="Carbon stocks in conterminous U.S. forests from 2001-2020."}
stockypes_live_dom_tec = c("Total Ecosystem", "Biomass: Total", "DOM: Deadwood")

stocks_ipcc = read_csv("data/results/stocks_conus.csv") %>%
  left_join(scenario_ids) %>%
  filter(StockGroupID %in% stockypes_live_dom_tec)

stocks_litter = c("DOM: Aboveground Very Fast [Type]", "DOM: Aboveground Fast [Type]")
stocks_soil = c("DOM: Aboveground Slow [Type]", "DOM: Belowground Slow [Type]", "DOM: Belowground Very Fast [Type]")

stocks_ipcc_litter = read_csv("data/results/stocks_conus.csv") %>%
  left_join(scenario_ids) %>%
  filter(StockGroupID %in% stocks_litter) %>%
  mutate(StockGroupID="DOM: Litter") %>%
  group_by(ScenarioID, Iteration, Timestep, ScenarioName, StockGroupID) %>%
  summarise(Amount=sum(Amount)) 

stocks_ipcc_soil= read_csv("data/results/stocks_conus.csv") %>%
  left_join(scenario_ids) %>%
  filter(StockGroupID %in% stocks_soil) %>%
  mutate(StockGroupID="DOM: Soil") %>%
  group_by(ScenarioID, Iteration, Timestep, ScenarioName, StockGroupID) %>%
  summarise(Amount=sum(Amount)) 

stocks_ipcc = bind_rows(stocks_ipcc, stocks_ipcc_litter, stocks_ipcc_soil)


ps1 = ggplot(stocks_ipcc, aes(x=Timestep, y=Amount/1000000, color=ScenarioName, fill=ScenarioName, shape=ScenarioName)) +
  geom_line() +
  scale_color_brewer(palette="Dark2") +
  geom_point(color="white", size=1.5) +
  scale_fill_brewer(palette="Dark2") +
  scale_shape_manual(values=c("LULC+Clim"=21, "Clim"=22, "LULC"=23, "Ref"=24)) +
  facet_wrap(~StockGroupID, scales="free_y", ncol=5) +
  theme_custom() +
  labs(x="Year", y=expression(Carbon~storage~(MMT~C)), fill="Scenario", shape="Scenario", color="Scenario") +
    theme(legend.position = "bottom",
        legend.key.width = unit(10, "mm"),
        legend.key.height = unit(3, "mm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-10,-10,0,-10))
```

```{r, stockchange, cache=T, echo=F, warning=F, message=F, fig.width=8, fig.height=4, fig.cap="Carbon stocks in conterminous U.S. forests from 2001-2020."}
stocks_ipcc_change = stocks_ipcc %>%
  filter(Timestep %in% c(2001,2020)) %>%
  arrange(Timestep) %>%
  group_by(ScenarioID, ScenarioName, Iteration, StockGroupID) %>%
  mutate(Change=Amount-lag(Amount)) %>%
  filter(Timestep==2020) %>% arrange(StockGroupID)

ps2 = ggplot(stocks_ipcc_change, aes(x=ScenarioName, y=Change/1000000, fill=ScenarioName)) +
  geom_bar(stat="identity") +
  scale_fill_brewer(palette = "Dark2") +
  facet_wrap(~StockGroupID, scales = "free_y", ncol=5) +
  geom_hline(yintercept = 0, size=0.2) +
  theme_custom() +
  labs(x=NULL, y=expression(Net~flux~(MMT~C)), fill="Scenario", shape="Scenario", color="Scenario") +
  theme(legend.position = "bottom",
        legend.key.width = unit(10, "mm"),
        legend.key.height = unit(3, "mm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-10,-10,0,-10),
        axis.text.x = element_blank())

plot_grid(ps1, ps2, align=c("hv"), nrow=2)
```

```{r, nbpmap, cache=T, echo=F, warning=F, message=F, fig.width=8, fig.cap="Map of the estiamted net biome productivity of conterminous U.S. forests for the period 2001-2020. Negative values indicate a net loss of carbon from ecosystems and positive values indicate a net sink of carbon."}
land_poly = st_read("data/vector/ne_10m_land.shp", quiet=T)
states_poly = st_read("data/vector/states.shp", quiet=T)
nbp_raster = raster("data/results/flows-nbp-2020.tif")
# nbp_raster = aggregate(nbp_raster, fact=4, na.rm=T)
nbp_raster_df = as.data.frame(nbp_raster, xy=T) %>%
  rename("Amount"="flows.nbp.2020") %>%
  filter(!is.na(Amount))
# 
# min(nbp_raster_df$Amount)
# max(nbp_raster_df$Amount)
# quantile(nbp_raster_df$Amount, probs = seq(0, 1, length.out = 9 + 1))

ggplot() +
  geom_sf(data=land_poly, aes(geometry=geometry), fill="white", color=NA) +
  geom_tile(data=nbp_raster_df, aes(x=x, y=y, fill=Amount)) +
  geom_sf(data=states_poly, aes(geometry=geometry), fill=NA, color="grey20", size=0.2) +
  coord_sf(crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs",
           xlim=c(min(nbp_raster_df$x), max(nbp_raster_df$x)),
           ylim=c(min(nbp_raster_df$y), max(nbp_raster_df$y))) +
  scale_fill_fermenter(palette = "BrBG", type="seq", direction=1, guide="colorsteps", breaks=c(-100,-20,-10,-5,-2,2,5,10,20, 50)) +
  labs(x=NULL, y=NULL, fill=expression(Metric~Tons~C~ha^-1)) +
  theme_bw() +
  theme(text=element_text(family="Roboto Condensed"),
        legend.position = c(0.2,0.1),
        legend.text.align = 0,
        legend.text = element_text(size = 7, hjust = 0, color = "#4e4d47"),
        legend.title = element_text(size = 8),
        plot.margin = unit(c(1,1,1,1), "mm"),
        legend.key.height = unit(2, "mm"),
        legend.key.width = unit(10, "mm"),
        axis.text.x = element_text(size=8),
        axis.text.y = element_text(size=8),
        panel.background = element_rect(fill="grey90")) +
  guides(fill = guide_colorsteps(direction = "horizontal",
                                 title.position = 'top',
                                 title.hjust = 0,
                                 label.hjust = 1,
                                 nrow = 1,
                                 byrow = T,
                                 reverse = F,
                                 label.position = "bottom",
                                 ticks = T,
                                 ticks.colour = "black",
                                 ticks.linewidth = 0.8,
                                 frame.colour = "black"))

```

```{r, tecmap, cache=T, echo=F, warning=F, message=F, fig.width=8, fig.cap="Map of the estiamted net biome productivity of conterminous U.S. forests for the period 2001-2020. Negative values indicate a net loss of carbon from ecosystems and positive values indicate a net sink of carbon."}
land_poly = st_read("data/vector/ne_10m_land.shp", quiet=T)
states_poly = st_read("data/vector/states.shp", quiet=T)
tec_raster = raster("data/results/stocks-tec-2020.tif")
# tec_raster = aggregate(tec_raster, fact=4, na.rm=T)
tec_raster_df = as.data.frame(tec_raster, xy=T) %>%
  rename("Amount"="stocks.tec.2020") %>%
  filter(Amount>0)

# min(tec_raster_df$Amount)
# max(tec_raster_df$Amount)
# quantile(tec_raster_df$Amount, probs = seq(0, 1, length.out = 9 + 1))

ggplot() +
  geom_sf(data=land_poly, aes(geometry=geometry), fill="white", color=NA) +
  geom_tile(data=tec_raster_df, aes(x=x, y=y, fill=Amount)) +
  geom_sf(data=states_poly, aes(geometry=geometry), fill=NA, color="grey20", size=0.2) +
  coord_sf(crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs",
           xlim=c(min(tec_raster_df$x), max(tec_raster_df$x)),
           ylim=c(min(tec_raster_df$y), max(tec_raster_df$y))) +
  scale_fill_fermenter(palette = "YlGnBu", type="seq", direction=1, guide="colorsteps", breaks=c(50,100,130,160,190,250,300,400)) +
  labs(x=NULL, y=NULL, fill=expression(Metric~Tons~C~ha^-1)) +
  theme_bw() +
  theme(text=element_text(family="Roboto Condensed"),
        legend.position = c(0.2,0.1),
        legend.text.align = 0,
        legend.text = element_text(size = 7, hjust = 0, color = "#4e4d47"),
        legend.title = element_text(size = 8),
        plot.margin = unit(c(1,1,1,1), "mm"),
        legend.key.height = unit(2, "mm"),
        legend.key.width = unit(10, "mm"),
        axis.text.x = element_text(size=8),
        axis.text.y = element_text(size=8),
        panel.background = element_rect(fill="grey90")) +
  guides(fill = guide_colorsteps(direction = "horizontal",
                                 title.position = 'top',
                                 title.hjust = 0,
                                 label.hjust = 1,
                                 nrow = 1,
                                 byrow = T,
                                 reverse = F,
                                 label.position = "bottom",
                                 ticks = T,
                                 ticks.colour = "black",
                                 ticks.linewidth = 0.8,
                                 frame.colour = "black"))

```
