# Discussion

This paper describes efforts to link the LUCAS state-and-transition simulation model with the CBM-CFS3 model of ecosystem carbon dynamics to produce detailed, spatially explicit estimates of land change and ecosystem carbon dynamics for the conterminous United States. The approach leverages the robust capabilities of LUCAS to represent a wide range of LULC and disturbance types derived from state of the art remote sensing techniques. We used the CBM-CFS3 model of carbon dynamics to parameterize a stock-flow sub-model and added a dynamic growth module to represent the effects of climate variability and change on the NPP of forested ecosytems. Results show strong agreement with a range of other studies, including those produced by inventory methods alone, such as the annual U.S. EPA greenhouse gas assessment. Because the method relies on the modeling of carbon fluxes to estimate stocks, the LUCAS-CBM approach provides the added benefit of providing rich detail in the underlying transfer of carbon between ecosystem pools, which is lacking in traditional inventory-based stock-change approaches. Additionally, because the model is parameterized at the pixel scale, all outputs are provided as a time-series of spatially explicit maps, providing much needed resolution suitable for land management decision making.

Results using the integrated LUCAS-CBM approach compare well with published results from a range of other studies utilizing a variety of methodological approaches. @hayes2012reconciling reviewed 17 terrestrial biosphere models and found a mean net ecosystem exchange (NEE) in U.S. forest of -157.6 (SD=309.5) Tg C yr^-1^ (here, negative values denote a net sink of carbon in ecosystems and product pools). The Second State of the Carbon Cycle Report (SOCCR2) estimated an net carbon sink of 154 Tg C yr^-1^ for U.S. forested ecosystems (forestland remaining forestland). Our estimate for the 2001-2010 period was a net sink of 159 Tg C yr^-1^, which compares well to both SOCCR2's inventory based approach and the estimate derived from process models.

The linked LUCAS-CBM approach provides a middle ground between inventory-based stock-change methods and complex process-based biogeochemical models. Our method overcomes many of the limitations of inventory based estimates, notable a lack of ability to attribute controlling processes, coarse temporal resolution, and typically a lack of spatially explicit estimates. Furthermore, inventory based methods often prioritize live biomass pools and in many cases under-sample other important DOM pools. We address each of these limitations while also utilizing detailed forest inventory data to parameterize key aspects of the the model. In this study we used merchantable volume curves derived from FIA data [@bechtold2005enhanced] to estimate standing stocks of carbon based on default biomass expansion factors and turnover rates from the CBM-CFS3 model.

Unlike inventory-based approaches, biogeochemical models represent a wide range of underlying processes and lend themselves well to attribution of change. By design, process models are also sensitive to the effects of weather and climate variability and change. However, the disadvantages of this class of models is their inherent complexity and large uncertainties resulting from the wide range of parameter estimates which need to be made [@hayes2012reconciling]. Furthermore, this class of models have been designed to work over large areas at relatively coarse resolution, which can be difficult to utilize at ecosystem management scales. The LUCAS-CBM approach was developed to overcome many of these obstacles by running on an annual timestep (as opposed to hourly or daily) and representing basic carbon transfer processes such as growth, mortality, turnover, decay, and decomposition. The relatively small number of carbon flux rates requiring parameterization still provides for attribution of change while reducing the internal complexity of the model. Furthermore, by incorporating the NPP sub-model to estimate variability in annual growth rates, our model is sensitive to the effects of climate variability and change. Lastly, the model framework we have developed is agnostic in terms of spatial resolution, meaning it can be run at any resolution across any sized landscape provided key inputs can be obtained (e.g. downscaled climate data) and computational resources are available.

The LUCAS model was designed using the SyncroSim modeling environment which originated as a tool to model landscape change [@daniel2016state]. As a result, the model contains a robust set of features to simulate a wide range of landscape change processes including vegetation dynamics [@ford2019tool; @miller2015combining], spread and management of invasive species [@jarnevich2020assessing], and habitat conservation [@d2019coupled]. We developed the LUCAS model to account for a variety of land-use and land-cover changes, including urbanization, agricultural expansion and contraction, fire, harvest, and drought mortality. However, features exist to include a range of other biophysical and socio-economic processes. For example, @wilson2016future used the LUCAS model to track changes in water use under alternative LULC scenarios and @sleeter2017projecting used the model to project changes in community vulnerability to coastal hazards. A range of studies have used LUCAS to assess ecosystem carbon dynamics, including a spatially explicit assessment for the state of Hawaii [@sleeter2017projected], an analysis of historical changes in the conterminous U.S. [@sleeter2018effects], and future projections for the state of California under alternative LULC and climate scenarios [@sleeter2019effects]. @sleeter2017carbon used a high resolution version of the LUCAS framework to model carbon dynamics in a forested peatland wildlife refuge in response to repeated stand replacing fires and changes in hydrologic land management [@sleeter2021enhanced].

The current implementation of the LUCAS-CBM approach utilizes a number of default parameters developed for forested ecosystem of Canada. For example, while we supplied U.S. specific merchantable growth rates based on FIA forest inventory data, we relied on the default biomass expansion factors from CBM-CFS3 to convert merchantable volume into carbon stock estimates. Additionally, we assigned each U.S. level 3 ecoregion and state to a corresponding Canadian ecozone and province so as to leverage existing DOM turnover rates. Default rates were then modified based on mean annual temperature for each U.S. region. Future research should focus on incorporating U.S. specific biomass expansion factors for individual tree species [@jenkins2003national] and incorporating regionally specific DOM turnover rates obtained from literature. Additionally, the LUCAS-CBM approach is well suited to exploring uncertainty in carbon model parameters by drawing from statistical distributions and then sampling using Monte Carlo methods. This capability is highly conducive to exploring uncertainties in model parameters through sensitivity analysis [@sleeter2019effects; @white2008practical].

The effect of CO~2~ fertilization is among the larger uncertainties associated with estimating the terrestrial carbon budget [@smith2016large]. It is not currently possible to model the effects of CO~2~ enrichment on forest productivity within the CBM-CFS3 model and thus was not included in this study. However, the effects of CO~2~ enrichment could be incorporated directly within the LUCAS framework through the use of a series of temporal growth multipliers much in the same way NPP variability was modeled. This approach was used by @sleeter2019effects to model the effects of CO~2~ enrichment on California ecosystems under multiple climate scenarios.

The effects of LULC and disturbance are a major controlling process of ecosystem carbon dynamics. However, uncertainties in LULC can be large, depending on the underlying source of data used. Advances in remote sensing have provide a new era of land change data for modelers, yet there are significant limitations when it comes to incorporating remote sensing data into carbon assessments. Large area and high temporal frequency data describing forest disturbance, such as the North American Forest Dynamics [@goward2012nacp]and the Global Forest Change [@hansen2013high] datasets are an important contribution towards our understanding of forest disturbance dynamics. However, attribution of forest changes - i.e. harvest, fire, drought, land use - are not yet provided. As a result, we relied on the Landfire Program's annual disturbance maps [@landfire2014disturbance], which provide change attribution data. Results suggest that based on Landfire disturbance data we underestimated the area of forest harvest, and in particular, the areal extent of selection harvest, which can be difficult to identify using synoptic-scale remote sensing data such as Landsat. Reconciling these differences should be a major point of emphasis for any carbon monitoring program.

The generalized modeling framework also allows for additional carbon stocks fluxes to be included, such as the lateral flux of carbon between terrestrial and aquatic ecosystems. While not included in this study, this lateral flux is considered an important factor in regional to global carbon budgets and estimated to account for \~1.0 Pg C yr^-1^ globally [@regnier2013anthropogenic] and is perhaps equal to the size of the total net terrestrial sink [@ciais2008impact]. The LUCAS framework is also well suited to tracking the fate of carbon resulting from other lateral fluxes, such as carbon removed in harvested products. @smyth2014quantifying used the CBM-CFS3 model linked with a harvested wood products (HWP) model that estimates emissions based on product half-life decay times to estimate carbon mitigation potential under alternative scenarios. The LUCAS framework readily allows for adding additional stock and flow pathways which could be used to track the fate of harvested carbon (see table \@ref(tab:lulcfluxtable)) through a range of product pools to provide a more complete understanding of forest carbon dynamics.

While we developed this study to analyze upland forested ecosystems, the framework can be extended to estimate carbon dynamics in other ecosystems as well, such as grasslands, shrublands, wetlands, agricultural lands, and urban/suburban landscapes. LUCAS has been used to model carbon dynamics in many of these systems using parameters derived from DGVM's [@sleeter2018effects]. Future research will focus on translating those parameters into the new LUCAS-CBM framework. Additionally, researchers are using the LUCAS framework, along with the carbon stock and flow structure adapted from the CBM-CFS3 and described in this paper, to develop a spatially explicit model of ecosystem carbon dynamics in coastal herbaceous wetlands [@stagg2020national].

Quantifying the effects of land management actions on carbon stocks and fluxes is increasingly needed to assess the effectiveness of natural climate solutions (NCS). The LUCAS-CBM approach is well suited to modeling the effectiveness of a range of NCS strategies, such as changing harvest rates and geographic patterns, protecting old growth forests, reducing deforestation, and implementing reforestation programs. To date, most studies aimed at quantifying the benefits of NCS have relied on non-spatial or spatially-referenced approaches which only factor in the biophysical suitability of reforestation [@fargione2018natural, @griscom2017natural] but do not consider other factors, such as areas that may provide additional co-benefits beyond increased carbon sequestration and storage [@cook2020lower]. The LUCAS-CBM approach described in this study, along with a new set of spatially explicit maps of reforestation potential [@cook2020lower], can be used to refine estimates carbon sequestration benefits.
