# Conclusion

Temperate forests of North America have been estimated as a large and persistent carbon sink over recent decades with U.S. forests accounting for the vast majority of the continental sink. However, uncertainty in the size and variability of the sink is large, owing primarily to the wide range of methodological approaches used to for estimation. Because the U.S. relies on a stock-change approach for its official reporting, there is a paucity of information and data on underlying carbon fluxes, making attribution of changes in the annual sink rate difficult. Additionally, while carbon stock-change estimates are updated annually, they are not spatially explicit, making utility by land managers difficult.

We developed a modeling approach to fill these important gaps. The approach described in this study was designed to serve as a middle ground between inventory-based stock-change methods and more complex process-based biogeochemical models. The LUCAS-CBM carbon monitoring and projection tool builds off a robust national forest inventory program with the added capability of producing spatially explicit carbon stocks and flows on an annual timestep. At the same time, the reduced complexity of the underlying system represented by the model makes the approach more accessible to a wider range of users. The approach is particularly well suited to producing rapid updates in response to major events (e.g. wildfire), assessing uncertainties of key parameters (e.g. CO~2~ fertilization, LULC change), or making projections over short, medium, or long time horizons. Lastly, the generalized structure of the modeling framework makes expanding the framework to cover other ecosystem types possible, as does including additional carbon flows such as lateral transfers between terrestrial and aquatic systems and harvested products.
