# Supplemental Material

```{r, echo=F}
trans_pal = c("Ag Expansion: Cropland" = "Peru",
              "Ag Expansion: Pasture" = "LightYellow",
              "Urbanization: High" = "Black",
              "Urbanization: Medium" = "DimGray",
              "Urbanization: Low" = "DarkGray",
              "Urbanization: Open" = "LightGray",
              "Forest Harvest: Forest Clearcut" = "Purple4",
              "Forest Harvest: Forest Selection" = "Purple1",
              "Fire: High Severity" = "DarkRed",
              "Fire: Medium Severity" = "Red",
              "Fire: Low Severity" = "Salmon",
              "Insect: High Severity" = "DarkGreen",
              "Insect: Medium Severity" = "Green3",
              "Insect: Low Severity" = "LightGreen") 

```

```{r, diagurb, cache=T, echo=F, warning=F, fig.width=3, Fig.height=3, fig.cap="Conceptual diagram of urbanization and urban intensification transitions used within the LUCAS state-and-transition simulation model."}

DiagrammeR::grViz("digraph rmarkdown{
graph [layout = dot, rankdir = LR]

node [shape = rectangle, fontname = 'Roboto Condensed', fixedsize = true, width=1]

node [style = filled; fillcolor = white]
Forest; Grassland; Shrubland; Wetland; Cropland; Pasture

node [shape = rectangle; style = filled; fillcolor = Gray90]
Urbanization

node [shape = rectangle; style = filled; fillcolor = Red4]
High

node [shape = rectangle; style = filled; fillcolor = OrangeRed]
Medium

node [shape = rectangle; style = filled; fillcolor = LightSalmon]
Low

node [shape = rectangle; style = filled; fillcolor = MistyRose]
Open

edge [arrowhead = vee, color = Red]
{Forest; Grassland; Shrubland; Wetland; Cropland; Pasture} -> Urbanization
Urbanization -> {High; Medium; Low; Open}

edge [arrowhead = normal, color = Black]
{Open} -> {Low; Medium; High}
{Low} -> {Medium; High}
{Medium} -> {High}

subgraph {rank = same; Open; Low; Medium; High}

}")
```

```{r, diagharv, cache=T, echo=F, warning=F, fig.width=3, Fig.height=3, fig.cap="Conceptual diagram of forest harvest transitions used within the LUCAS state-and-transition simulation model."}

DiagrammeR::grViz("digraph rmarkdown{
graph [layout = dot, rankdir = TB]

node [fontname = 'Roboto Condensed', fixedsize = true, fontsize = 8]
edge [fontname= 'Roboto Condensed', fontsize = 7]

node [shape = rectangle, style = filled; fillcolor = ForestGreen]
Forest

node [shape = rectangle; style = filled; fillcolor = Gray90]
Clearcut; Selection

edge [arrowhead = vee, color = black, font = 'Universe Condensed']
Forest -> {Harvest} [label = 'Annual area']
Harvest -> Clearcut [label = 'Harvest multipliers', style = dashed]
Harvest -> Selection [style = dashed]

Clearcut -> Forest [label = 'regrowth']
Selection -> Forest

subgraph {rank = same; Clearcut; Selection}

}")
```

```{r, diagfire, cache=T, echo=F, warning=F, fig.width=3, Fig.height=3, fig.cap="Conceptual diagram of wildfire transitions used within the LUCAS state-and-transition simulation model."}

DiagrammeR::grViz("digraph rmarkdown{
graph [layout = dot, rankdir = TB]

node [fontname = 'Roboto Condensed', fixedsize = true, fontsize = 8]
edge [fontname= 'Roboto Condensed', fontsize = 7]

node [shape = rectangle, style = filled; fillcolor = ForestGreen]
Forest

node [shape = rectangle, style = filled; fillcolor = '#DCCA8F']
Shrubland


node [shape = rectangle; style = filled; fillcolor = Gray90]
Fire

node [shape = rectangle; style = filled; fillcolor = Gray90]
High; Medium; Low

edge [arrowhead = vee, color = black, font = 'Universe Condensed']
Forest -> Fire [label = 'Annual Perimeters']
Fire -> High [style = dashed]
Fire -> Medium [label = 'severity multiplier'; style = dashed]
Fire -> Low [style = dashed]

{Medium; Low} -> Forest
High -> Shrubland
Shrubland -> Forest [label = 'regrowth multiplier'; style = dashed]

Forest -> Selection
Selection -> Prescribed
Prescribed -> Low
Prescribed -> Medium

subgraph {rank = same; High; Medium; Low}
subgraph {rank = same; Shrubland; Forest}

}")
```


```{r, stockresults, cache=T, echo=F, warning=F, message=F, fig.width=8, fig.height=4, fig.cap="Carbon stocks in conterminous U.S. forests from 2001-2020."}

ggplot(stocks_ipcc, aes(x=Timestep, y=Amount/1000000, color=ScenarioName, fill=ScenarioName, shape=ScenarioName)) +
  geom_line() +
  scale_color_brewer(palette="Set2") +
  geom_point(color="white", size=1.5) +
  scale_fill_brewer(palette="Set2") +
  scale_shape_manual(values=c("LULC+Clim"=21, "Clim"=22, "LULC"=23, "Ref"=24)) +
  facet_wrap(~StockGroupID, scales="free_y", ncol=5) +
  theme_custom() +
  labs(x="Year", y=expression(Carbon~storage~(MMT~C)), fill="Scenario", shape="Scenario", color="Scenario") +
    theme(legend.position = "bottom",
        legend.key.width = unit(10, "mm"),
        legend.key.height = unit(3, "mm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-10,-10,0,-10))
```

```{r, stocksstateclass, echo=F, warning=F, message=F, fig.width=6, fig.height=6, fig.cap="Net change in carbon stock for each forest type and state class."}

stocks_state_class = read_csv("data/results/stocks-state-class.csv") %>%
  left_join(scenario_ids) %>%
  filter(StockGroupID %in% c("Biomass: Aboveground", "Biomass: Belowground", "DOM: Deadwood", "DOM: Litter", "DOM: Soil"), Timestep %in% c(2001,2020), ScenarioName=="LULC+Clim") %>%
  group_by(ScenarioName, StockGroupID, StateClassID) %>%
  arrange(Timestep) %>%
  mutate(Change = Amount-lag(Amount)) %>%
  filter(Timestep==2020, Change!=0) %>%
  mutate(StateClassID = str_remove(StateClassID, " Group"))

tec_state_class = stocks_state_class %>%
  group_by(StateClassID) %>% summarise(Amount=sum(Amount), Change=sum(Change)) %>%
  mutate(StockGroupID = "Total Ecosystem")

ggplot() +
  geom_bar(data=stocks_state_class, aes(x=StateClassID, y=Change/1000000, fill=StockGroupID), stat="identity") +
  geom_segment(data=tec_state_class, aes(x=StateClassID, xend=StateClassID, yend=0, y=Change/1000000, color="TEC")) +
  geom_point(data=tec_state_class, aes(x=StateClassID, y=Change/1000000, color="TEC"), shape=16) +
  scale_color_manual(values = c("TEC"="black")) +
  scale_fill_brewer(palette = "Set2") +
  scale_y_continuous(labels = comma) +
  coord_flip() +
  labs(x=NULL, y=expression(MMT~C), color=NULL, fill="Stock Group") +
  theme_custom() +
  theme(legend.position = c(0.8,0.1),
        legend.direction = "vertical",
        legend.key.height = unit(2, "mm"),
        legend.margin = margin(-1,-1,-10,-10))

```

Total ecosystem carbon (TEC) is the sum of all carbon stored in ecosystem pools (i.e. above and belowground biomass, deadwood, litter, and soil). The areas with the largest carbon stores were generally in the western mountain regions which often stored in excess of 300 tons per hectare.

```{r, tecmap, cache=T, echo=F, warning=F, message=F, fig.width=8, fig.cap="Map of the total ecosystem carbon stored in conterminous U.S. forests in the year 2020."}
land_poly = st_read("data/vector/ne_10m_land.shp", quiet=T)
states_poly = st_read("data/vector/states.shp", quiet=T)
tec_raster = raster("data/results/stocks-tec-2020.tif")
# tec_raster = aggregate(tec_raster, fact=4, na.rm=T)
tec_raster_df = as.data.frame(tec_raster, xy=T) %>%
  rename("Amount"="stocks.tec.2020") %>%
  filter(Amount>0)

breaks = c(min(tec_raster_df$Amount),50,100,150,200,300,max(tec_raster_df$Amount))
tec_raster_df = tec_raster_df %>% mutate(Class = cut(Amount, breaks=breaks, right=F))
unique(tec_raster_df$Class)

# min(tec_raster_df$Amount)
# max(tec_raster_df$Amount)
# quantile(tec_raster_df$Amount, probs = seq(0, 1, length.out = 9 + 1))

ggplot() +
  geom_sf(data=land_poly, aes(geometry=geometry), fill="white", color=NA) +
  geom_tile(data=tec_raster_df, aes(x=x, y=y, fill=Amount)) +
  geom_sf(data=states_poly, aes(geometry=geometry), fill=NA, color="grey20", size=0.2) +
  coord_sf(crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs",
           xlim=c(min(tec_raster_df$x), max(tec_raster_df$x)),
           ylim=c(min(tec_raster_df$y), max(tec_raster_df$y))) +
  scale_fill_fermenter(palette = "YlGnBu", type="seq", direction=1, guide="colorsteps", breaks=c(50,100,130,160,190,250,300,400)) + 
  #scale_fill_manual(values=c("grey90", "grey50", "lightyellow", "orange", "forestgreen", "purple"), guide="colorsteps") +
  labs(x=NULL, y=NULL, fill=expression(Metric~Tons~C~ha^-1)) +
  theme_bw() +
  theme(text=element_text(family="Roboto Condensed"),
        legend.position = c(0.2,0.1),
        legend.text.align = 0,
        legend.text = element_text(size = 7, hjust = 0, color = "#4e4d47"),
        legend.title = element_text(size = 8),
        plot.margin = unit(c(1,1,1,1), "mm"),
        legend.key.height = unit(2, "mm"),
        legend.key.width = unit(10, "mm"),
        axis.text.x = element_text(size=8),
        axis.text.y = element_text(size=8),
        panel.background = element_rect(fill="grey90")) +
  guides(fill = guide_colorsteps(direction = "horizontal",
                                 title.position = 'top',
                                 title.hjust = 0,
                                 label.hjust = 1,
                                 nrow = 1,
                                 byrow = T,
                                 reverse = F,
                                 label.position = "bottom",
                                 ticks = T,
                                 ticks.colour = "black",
                                 ticks.linewidth = 0.8,
                                 frame.colour = "black"))

```

```{r, stateclasstecchange, cache=T, echo=F, warning=F, message=F, fig.width=8, fig.height=4}
stocks_state_class = read_csv("data/results/stocks-state-class.csv") %>%
  left_join(scenario_ids) %>%
  filter(ScenarioName == "LULC+Clim", StockGroupID == "Total Ecosystem", str_detect(StateClassID, "Forest:")) %>%
  mutate(Amount=Amount/1000000) %>%
  filter(Timestep %in% c(2001,2020)) %>%
  group_by(StateClassID) %>%
  arrange(Timestep) %>%
  mutate(Change = Amount-lag(Amount)) %>%
  filter(Timestep == 2020)
stocks_state_class

ggplot(stocks_state_class, aes(x=fct_reorder(StateClassID, Change), y=Change, fill=StateClassID)) +
  geom_bar(stat="identity", show.legend = F) +
  coord_flip() +
  theme_custom() +
  labs(x=NULL, y=expression(Net~flux~(MMT~C)), fill="Scenario", shape="Scenario", color="Scenario") +
  theme(legend.position = c(0.85,0.2),
        legend.key.width = unit(5, "mm"),
        legend.key.height = unit(3, "mm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-10,-10,0,-10))

```
