<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Results | Spatially explicit estimates of carbon stocks and fluxes for the United States: a new approach linking the LUCAS and CBM-CFS3 models</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Results | Spatially explicit estimates of carbon stocks and fluxes for the United States: a new approach linking the LUCAS and CBM-CFS3 models" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Results | Spatially explicit estimates of carbon stocks and fluxes for the United States: a new approach linking the LUCAS and CBM-CFS3 models" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Benjamin M. Sleeter" />


<meta name="date" content="2021-03-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="discussion.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>



<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Abstract</a></li>
<li class="chapter" data-level="2" data-path="abstract-1.html"><a href="abstract-1.html"><i class="fa fa-check"></i><b>2</b> Abstract</a></li>
<li class="chapter" data-level="3" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>3</b> Introduction</a></li>
<li class="chapter" data-level="4" data-path="results.html"><a href="results.html"><i class="fa fa-check"></i><b>4</b> Results</a>
<ul>
<li class="chapter" data-level="4.1" data-path="results.html"><a href="results.html#estimation-of-carbon-storage-in-live-dead-and-soil-pools"><i class="fa fa-check"></i><b>4.1</b> Estimation of carbon storage in live, dead, and soil pools</a></li>
<li class="chapter" data-level="4.2" data-path="results.html"><a href="results.html#net-change-in-ecosystem-carbon-storage"><i class="fa fa-check"></i><b>4.2</b> Net change in ecosystem carbon storage</a></li>
<li class="chapter" data-level="4.3" data-path="results.html"><a href="results.html#net-change-in-carbon-stocks"><i class="fa fa-check"></i><b>4.3</b> Net change in carbon stocks</a></li>
<li class="chapter" data-level="4.4" data-path="results.html"><a href="results.html#carbon-fluxes"><i class="fa fa-check"></i><b>4.4</b> Carbon fluxes</a></li>
<li class="chapter" data-level="4.5" data-path="results.html"><a href="results.html#effects-of-lulc-and-disturbance"><i class="fa fa-check"></i><b>4.5</b> Effects of LULC and disturbance</a></li>
<li class="chapter" data-level="4.6" data-path="results.html"><a href="results.html#projections-of-carbon-change"><i class="fa fa-check"></i><b>4.6</b> Projections of carbon change</a></li>
<li class="chapter" data-level="4.7" data-path="results.html"><a href="results.html#carbon-emissions-from-wildfire-in-california"><i class="fa fa-check"></i><b>4.7</b> Carbon emissions from wildfire in California</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="discussion.html"><a href="discussion.html"><i class="fa fa-check"></i><b>5</b> Discussion</a></li>
<li class="chapter" data-level="6" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>6</b> Conclusion</a></li>
<li class="chapter" data-level="7" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>7</b> Methods</a>
<ul>
<li class="chapter" data-level="7.1" data-path="methods.html"><a href="methods.html#lucas-state-and-transition-simulation-model"><i class="fa fa-check"></i><b>7.1</b> LUCAS state-and-transition simulation model</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="methods.html"><a href="methods.html#state-class-map"><i class="fa fa-check"></i><b>7.1.1</b> State class map</a></li>
<li class="chapter" data-level="7.1.2" data-path="methods.html"><a href="methods.html#forest-age"><i class="fa fa-check"></i><b>7.1.2</b> Forest age</a></li>
<li class="chapter" data-level="7.1.3" data-path="methods.html"><a href="methods.html#lulc-and-disturbance-transitions"><i class="fa fa-check"></i><b>7.1.3</b> LULC and disturbance transitions</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="methods.html"><a href="methods.html#lucas-carbon-stock-and-flows"><i class="fa fa-check"></i><b>7.2</b> LUCAS carbon stock and flows</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="methods.html"><a href="methods.html#cbm-cfs3-reference-simulations"><i class="fa fa-check"></i><b>7.2.1</b> CBM-CFS3 reference simulations</a></li>
<li class="chapter" data-level="7.2.2" data-path="methods.html"><a href="methods.html#carbon-flow-rates-lucas-flow-pathways-module"><i class="fa fa-check"></i><b>7.2.2</b> Carbon flow rates: LUCAS Flow Pathways module</a></li>
<li class="chapter" data-level="7.2.3" data-path="methods.html"><a href="methods.html#validation"><i class="fa fa-check"></i><b>7.2.3</b> Validation</a></li>
<li class="chapter" data-level="7.2.4" data-path="methods.html"><a href="methods.html#spin-up-of-dom-pools"><i class="fa fa-check"></i><b>7.2.4</b> Spin-up of DOM pools</a></li>
<li class="chapter" data-level="7.2.5" data-path="methods.html"><a href="methods.html#mapping-initial-carbon-stocks"><i class="fa fa-check"></i><b>7.2.5</b> Mapping initial carbon stocks</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="methods.html"><a href="methods.html#spatial-flow-multipliers"><i class="fa fa-check"></i><b>7.3</b> Spatial flow multipliers</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="methods.html"><a href="methods.html#npp-variability"><i class="fa fa-check"></i><b>7.3.1</b> NPP variability</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="intro.html"><a href="intro.html#intro"><i class="fa fa-check"></i><b>8</b> Introduction</a></li>
<li class="chapter" data-level="9" data-path="results-1.html"><a href="results-1.html"><i class="fa fa-check"></i><b>9</b> Results</a>
<ul>
<li class="chapter" data-level="9.1" data-path="results-1.html"><a href="results-1.html#estimation-of-carbon-storage-in-live-dead-and-soil-pools-1"><i class="fa fa-check"></i><b>9.1</b> Estimation of carbon storage in live, dead, and soil pools</a></li>
<li class="chapter" data-level="9.2" data-path="results-1.html"><a href="results-1.html#net-change-in-ecosystem-carbon-storage-1"><i class="fa fa-check"></i><b>9.2</b> Net change in ecosystem carbon storage</a></li>
<li class="chapter" data-level="9.3" data-path="results-1.html"><a href="results-1.html#net-change-in-carbon-stocks-1"><i class="fa fa-check"></i><b>9.3</b> Net change in carbon stocks</a></li>
<li class="chapter" data-level="9.4" data-path="results-1.html"><a href="results-1.html#carbon-fluxes-1"><i class="fa fa-check"></i><b>9.4</b> Carbon fluxes</a></li>
<li class="chapter" data-level="9.5" data-path="results-1.html"><a href="results-1.html#effects-of-lulc-and-disturbance-1"><i class="fa fa-check"></i><b>9.5</b> Effects of LULC and disturbance</a></li>
<li class="chapter" data-level="9.6" data-path="results-1.html"><a href="results-1.html#projections-of-carbon-change-1"><i class="fa fa-check"></i><b>9.6</b> Projections of carbon change</a></li>
<li class="chapter" data-level="9.7" data-path="results-1.html"><a href="results-1.html#carbon-emissions-from-wildfire-in-california-1"><i class="fa fa-check"></i><b>9.7</b> Carbon emissions from wildfire in California</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="discussion-1.html"><a href="discussion-1.html"><i class="fa fa-check"></i><b>10</b> Discussion</a></li>
<li class="chapter" data-level="11" data-path="conclusion-1.html"><a href="conclusion-1.html"><i class="fa fa-check"></i><b>11</b> Conclusion</a></li>
<li class="chapter" data-level="12" data-path="methods-1.html"><a href="methods-1.html"><i class="fa fa-check"></i><b>12</b> Methods</a>
<ul>
<li class="chapter" data-level="12.1" data-path="methods-1.html"><a href="methods-1.html#lucas-state-and-transition-simulation-model-1"><i class="fa fa-check"></i><b>12.1</b> LUCAS state-and-transition simulation model</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="methods-1.html"><a href="methods-1.html#state-class-map-1"><i class="fa fa-check"></i><b>12.1.1</b> State class map</a></li>
<li class="chapter" data-level="12.1.2" data-path="methods-1.html"><a href="methods-1.html#forest-age-1"><i class="fa fa-check"></i><b>12.1.2</b> Forest age</a></li>
<li class="chapter" data-level="12.1.3" data-path="methods-1.html"><a href="methods-1.html#lulc-and-disturbance-transitions-1"><i class="fa fa-check"></i><b>12.1.3</b> LULC and disturbance transitions</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="methods-1.html"><a href="methods-1.html#lucas-carbon-stock-and-flows-1"><i class="fa fa-check"></i><b>12.2</b> LUCAS carbon stock and flows</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="methods-1.html"><a href="methods-1.html#cbm-cfs3-reference-simulations-1"><i class="fa fa-check"></i><b>12.2.1</b> CBM-CFS3 reference simulations</a></li>
<li class="chapter" data-level="12.2.2" data-path="methods-1.html"><a href="methods-1.html#carbon-flow-rates-lucas-flow-pathways-module-1"><i class="fa fa-check"></i><b>12.2.2</b> Carbon flow rates: LUCAS Flow Pathways module</a></li>
<li class="chapter" data-level="12.2.3" data-path="methods-1.html"><a href="methods-1.html#validation-1"><i class="fa fa-check"></i><b>12.2.3</b> Validation</a></li>
<li class="chapter" data-level="12.2.4" data-path="methods-1.html"><a href="methods-1.html#spin-up-of-dom-pools-1"><i class="fa fa-check"></i><b>12.2.4</b> Spin-up of DOM pools</a></li>
<li class="chapter" data-level="12.2.5" data-path="methods-1.html"><a href="methods-1.html#mapping-initial-carbon-stocks-1"><i class="fa fa-check"></i><b>12.2.5</b> Mapping initial carbon stocks</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="methods-1.html"><a href="methods-1.html#spatial-flow-multipliers-1"><i class="fa fa-check"></i><b>12.3</b> Spatial flow multipliers</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="methods-1.html"><a href="methods-1.html#npp-variability-1"><i class="fa fa-check"></i><b>12.3.1</b> NPP variability</a></li>
<li class="chapter" data-level="12.3.2" data-path="methods-1.html"><a href="methods-1.html#decay-and-decomposition-of-dom"><i class="fa fa-check"></i><b>12.3.2</b> Decay and decomposition of DOM</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="methods-1.html"><a href="methods-1.html#scenario-simulations"><i class="fa fa-check"></i><b>12.4</b> Scenario simulations</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="13" data-path="supplemental-material.html"><a href="supplemental-material.html"><i class="fa fa-check"></i><b>13</b> Supplemental Material</a>
<ul>
<li class="chapter" data-level="13.1" data-path="supplemental-material.html"><a href="supplemental-material.html#regional-variability"><i class="fa fa-check"></i><b>13.1</b> Regional variability</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Spatially explicit estimates of carbon stocks and fluxes for the United States: a new approach linking the LUCAS and CBM-CFS3 models</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="results" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Results</h1>
<p>The integrated modeling approach described in this paper produces estimates of the composition of state classes and their attributes (e.g. age, time-since-transition), LULC transitions, carbon stocks, and carbon fluxes. For each variable type, the model can output both spatially explicit (i.e. raster maps) and spatially referenced estimates. Spatially referenced results are provided for each of the three stratifications used in the model (i.e. ecoregions, states, and ownership). For the purposes of this study, we highlight the carbon stock and flux results derived from four unique scenario simulations where a) the combined effects of climate and LULC were modeled (“LULC-D + Climate”), b) only climate effects were considered (“Climate Only”), c) only land use/land cover and disturbances were considered (“LULC-D Only”), and d) neither LULC or climate were included (“No Effects”).</p>
<div id="estimation-of-carbon-storage-in-live-dead-and-soil-pools" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Estimation of carbon storage in live, dead, and soil pools</h2>
<p>Using the linked LUCAS-CBM modeling approach, we estimated total ecosystem carbon storage (TEC; the sum of all carbon stored in live, DOM, and soil pools) in forested ecosystems of the conterminous U.S. was 52,027 Tg C. Live carbon accounted for 31% (16,201 Tg C) of TEC while DOM pools accounted for 69% (35,826 Tg C). Within DOM pools, standing and down deadwood accounted for 5% (2,731 Tg C), litter accounted for 4% (2,239 Tg C), and soil organic carbon accounted for 59% (30,856 Tg C) of TEC.</p>
<p>Our estimates of carbon storage compare well with other recent studies (Fig. <a href="results.html#fig:studycomparisonfig">4.1</a>). For example, for the most recent national greenhouse gas inventory, the U.S. Environmental Protection Agency estimated forested ecosystems stored 17,940 Tg C <span class="citation">(<a href="supplemental-material.html#ref-epa2020inventory" role="doc-biblioref">U.S. EPA 2020</a>)</span> in live biomass, slightly higher than our estimate of 16,201 Tg C (mean estimated over the 2001-2010 period). When normalizing for differences in forest area, EPA estimated carbon storage in live vegetation was 64.1 tons C ha<sup>-1</sup>, compared to our estimate of 60.3 tons C ha<sup>-1</sup>. Other carbon pool estimates also compared well with those from the EPA. We estimated carbon stored in dead biomass averaged 10.2 tons C ha<sup>-1</sup> compared to EPA’s estimate of 9.8 tons C ha<sup>-1</sup>, while soil carbon storage was estimated at 114.8 tons C ha<sup>-1</sup> compared to EPA’s estimate of 112.8 tons C ha<sup>-1</sup>. Our estimates of litter carbon density (8.3 tons C ha<sup>-1</sup>) were towards to lower range of other studies and comparable to estimates from <span class="citation"><a href="supplemental-material.html#ref-wilson2013imputing" role="doc-biblioref">B. T. Wilson, Woodall, and Griffith</a> (<a href="supplemental-material.html#ref-wilson2013imputing" role="doc-biblioref">2013</a>)</span> (9.7 tons C ha<sup>-1</sup>) and <span class="citation"><a href="supplemental-material.html#ref-usgcrp2018soccr2" role="doc-biblioref">USGCRP</a> (<a href="supplemental-material.html#ref-usgcrp2018soccr2" role="doc-biblioref">2018</a>)</span> (8.8 tons C ha<sup>-1</sup>), while the EPA estimated litter carbon density at 13 tons C ha<sup>-1</sup>.</p>
<div class="figure"><span id="fig:studycomparisonfig"></span>
<img src="test_files/figure-html/studycomparisonfig-1.png" alt="Comparison of estimates of carbon stocks with other studies." width="768" />
<p class="caption">
Figure 4.1: Comparison of estimates of carbon stocks with other studies.
</p>
</div>
</div>
<div id="net-change-in-ecosystem-carbon-storage" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Net change in ecosystem carbon storage</h2>
<p>Between 2001 and 2020, total forest carbon storage increased from 52,027 Tg C to 54,413 Tg C, resulting in a forest carbon sink of 2,386 Tg C over the 19-year period. On an annualized basis, the net forest carbon sink was estimated to be 126 Tg C yr<sup>-1</sup>, or 0.47 Tons C ha<sup>-1</sup> yr<sup>-1</sup>. We estimated large variability in the size of the forest carbon sink over time, primarily due to the effects of weather and climate variability and its resulting effect on net primary production (NPP); variability in the rate of disturbance also played an important role, especially in the later part of the study period. For the 2001-2010 period we estimated the net forest sink to be 159 Tg C yr<sup>-1</sup> compared to 95 Tg C yr<sup>-1</sup> for the 2011-2020 period. On an annual basis, NBP ranged from a sink of 236 Tg C yr<sup>-1</sup> to a net source at a rate of -31 Tg C yr<sup>-1</sup>. Figure <a href="results.html#fig:nbpmap">4.2</a> shows the spatial distribution of NBP. Forests in California and the Southeast were the largest drivers of carbon loss, with fire driving a majority of the change in the west and forest harvest driving changes in the Southeast. The largest sinks of carbon were located in the coastal Pacific Northwest and in Redwood forests of California.</p>
<p>Comparison of net carbon flux estimates between models and approaches can be difficult due to differences in boundary conditions, modeled ecosystem processes, and the temporal period covered. In general, our estimates of NBP are within the range of numerous other studies which generally range from a low of 47 Tg C yr<sup>-1</sup> <span class="citation">(<a href="supplemental-material.html#ref-williams2012carbon" role="doc-biblioref">Williams et al. 2012</a>)</span> to a high of 282 Tg C yr<sup>-1</sup> <span class="citation">(<a href="supplemental-material.html#ref-hayes2012reconciling" role="doc-biblioref">Hayes et al. 2012</a>)</span>. <span class="citation"><a href="supplemental-material.html#ref-hayes2012reconciling" role="doc-biblioref">Hayes et al.</a> (<a href="supplemental-material.html#ref-hayes2012reconciling" role="doc-biblioref">2012</a>)</span> found that on average, atmospheric inversion (282 Tg C yr<sup>-1</sup>) and inventory-based methods (244 Tg C yr<sup>-1</sup>) produced higher estimates of the net forest carbon sink than estimates derived using terrestrial biosphere models (158 Tg C yr<sup>-1</sup>). However, all approaches showed large uncertainties. The Second State of the Carbon Cycle Report <span class="citation">(<a href="supplemental-material.html#ref-usgcrp2018soccr2" role="doc-biblioref">USGCRP 2018</a>)</span> estimated the U.S. forest carbon sink at 178 Tg C yr<sup>-1</sup> for the period 2000-2014. When accounting for differences in land area, the mean sink rate was 0.58 tons C ha<sup>-1</sup> yr<sup>-1</sup>. Over a similar period (2001-2014), the LUCAS-CBM approach estimated a net sink rate of 0.52 tons C ha<sup>-1</sup> yr<sup>-1</sup>. Using a process-based dynamic global vegetation model, <span class="citation"><a href="supplemental-material.html#ref-liu2020critical" role="doc-biblioref">J. Liu et al.</a> (<a href="supplemental-material.html#ref-liu2020critical" role="doc-biblioref">2020</a>)</span> estimated the net forest sink at 125 Tg C yr<sup>-1</sup> while over the same period we estimated the net sink at 159 Tg C yr<sup>-1</sup>, which was similar to the mean estimate of terrestrial biosphere models evaluated by <span class="citation"><a href="supplemental-material.html#ref-hayes2012reconciling" role="doc-biblioref">Hayes et al.</a> (<a href="supplemental-material.html#ref-hayes2012reconciling" role="doc-biblioref">2012</a>)</span>.</p>
<div class="figure"><span id="fig:nbpmap"></span>
<img src="test_files/figure-html/nbpmap-1.png" alt="Map of the estiamted net biome productivity of conterminous U.S. forests for the period 2001-2020. Negative values indicate a net loss of carbon from ecosystems and positive values indicate a net sink of carbon." width="768" />
<p class="caption">
Figure 4.2: Map of the estiamted net biome productivity of conterminous U.S. forests for the period 2001-2020. Negative values indicate a net loss of carbon from ecosystems and positive values indicate a net sink of carbon.
</p>
</div>
</div>
<div id="net-change-in-carbon-stocks" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Net change in carbon stocks</h2>
<p>Increases in ecosystem carbon were primarily the result of increases in carbon stored in live biomass (Table <a href="results.html#tab:stocktable">4.1</a>). We estimated live carbon pools increased from 16,201 Tg C to 18,890 Tg C, a net increase of 2,689 (0.17%). Merchantable carbon had the largest increase in both amount (1,649 Tg C) and as a percentage of 2001 stock levels (21%), followed by branches and other wood (537 Tg C; 12.5%) and coarse roots (418 Tg C; 15.5%). In total, aboveground live carbon increased by 17.3% and belowground live carbon increased by 13.8% .</p>
<p>Carbon stored in dead organic matter (DOM) pools, including deadwood, litter, and soil, remained relatively stable, declining by -0.8% (-303 Tg C) over the study period. Total carbon stored in deadwood and litter increased by 1.7% and 1.6%, respectively while soil carbon declined by -1.2%. However, the net change in DOM masked important internal dynamics (Table <a href="results.html#tab:stocktable">4.1</a>). For example, carbon stored in standing dead snags increased by 35.8% while downed deadwood (i.e. “DOM: Aboveground Medium”) declined by -18.1% with the increase in standing deadwood the result of increases in area impacted by wildfire.</p>
<table class=" lightable-classic lightable-striped" style="font-size: 12px; font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
<caption style="font-size: initial !important;">
<span id="tab:stocktable">Table 4.1: </span>Carbon stock estimates for forest ecosystems of the conterminous U.S.. Units are in Tg C.
</caption>
<thead>
<tr>
<th style="empty-cells: hide;" colspan="1">
</th>
<th style="padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="TRUE">
Year
</div>
</th>
<th style="padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="TRUE">
Change
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Stock
</th>
<th style="text-align:right;">
2001
</th>
<th style="text-align:right;">
2020
</th>
<th style="text-align:right;">
Tg C
</th>
<th style="text-align:right;">
%
</th>
</tr>
</thead>
<tbody>
<tr grouplength="4">
<td colspan="5" style="border-bottom: 1px solid;">
<strong>Aboveground live</strong>
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
Biomass: Foliage [Type]
</td>
<td style="text-align:right;">
881.5
</td>
<td style="text-align:right;">
949.2
</td>
<td style="text-align:right;">
67.7
</td>
<td style="text-align:right;">
7.7
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
Biomass: Merchantable [Type]
</td>
<td style="text-align:right;">
7859.7
</td>
<td style="text-align:right;">
9508.9
</td>
<td style="text-align:right;">
1649.2
</td>
<td style="text-align:right;">
21.0
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
Biomass: Other Wood [Type]
</td>
<td style="text-align:right;">
4306.0
</td>
<td style="text-align:right;">
4842.6
</td>
<td style="text-align:right;">
536.6
</td>
<td style="text-align:right;">
12.5
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
Total
</td>
<td style="text-align:right;">
13047.1
</td>
<td style="text-align:right;">
15300.7
</td>
<td style="text-align:right;">
2253.5
</td>
<td style="text-align:right;">
17.3
</td>
</tr>
<tr grouplength="3">
<td colspan="5" style="border-bottom: 1px solid;">
<strong>Belowground live</strong>
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
Biomass: Coarse Root [Type]
</td>
<td style="text-align:right;">
2689.4
</td>
<td style="text-align:right;">
3107.0
</td>
<td style="text-align:right;">
417.6
</td>
<td style="text-align:right;">
15.5
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
Biomass: Fine Root [Type]
</td>
<td style="text-align:right;">
464.6
</td>
<td style="text-align:right;">
482.3
</td>
<td style="text-align:right;">
17.7
</td>
<td style="text-align:right;">
3.8
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
Total
</td>
<td style="text-align:right;">
3154.1
</td>
<td style="text-align:right;">
3589.3
</td>
<td style="text-align:right;">
435.3
</td>
<td style="text-align:right;">
13.8
</td>
</tr>
<tr grouplength="5">
<td colspan="5" style="border-bottom: 1px solid;">
<strong>Deadwood</strong>
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
DOM: Aboveground Medium [Type]
</td>
<td style="text-align:right;">
1488.9
</td>
<td style="text-align:right;">
1219.4
</td>
<td style="text-align:right;">
-269.6
</td>
<td style="text-align:right;">
-18.1
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
DOM: Belowground Fast [Type]
</td>
<td style="text-align:right;">
246.9
</td>
<td style="text-align:right;">
247.4
</td>
<td style="text-align:right;">
0.5
</td>
<td style="text-align:right;">
0.2
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
DOM: Snag Branch [Type]
</td>
<td style="text-align:right;">
238.6
</td>
<td style="text-align:right;">
281.8
</td>
<td style="text-align:right;">
43.3
</td>
<td style="text-align:right;">
18.1
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
DOM: Snag Stem [Type]
</td>
<td style="text-align:right;">
756.9
</td>
<td style="text-align:right;">
1028.2
</td>
<td style="text-align:right;">
271.3
</td>
<td style="text-align:right;">
35.8
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
Total
</td>
<td style="text-align:right;">
2731.3
</td>
<td style="text-align:right;">
2776.8
</td>
<td style="text-align:right;">
45.5
</td>
<td style="text-align:right;">
1.7
</td>
</tr>
<tr grouplength="3">
<td colspan="5" style="border-bottom: 1px solid;">
<strong>Litter</strong>
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
DOM: Aboveground Fast [Type]
</td>
<td style="text-align:right;">
1382.9
</td>
<td style="text-align:right;">
1369.6
</td>
<td style="text-align:right;">
-13.2
</td>
<td style="text-align:right;">
-1.0
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
DOM: Aboveground Very Fast [Type]
</td>
<td style="text-align:right;">
856.0
</td>
<td style="text-align:right;">
904.2
</td>
<td style="text-align:right;">
48.2
</td>
<td style="text-align:right;">
5.6
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
Total
</td>
<td style="text-align:right;">
2238.9
</td>
<td style="text-align:right;">
2273.9
</td>
<td style="text-align:right;">
35.0
</td>
<td style="text-align:right;">
1.6
</td>
</tr>
<tr grouplength="4">
<td colspan="5" style="border-bottom: 1px solid;">
<strong>Soil</strong>
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
DOM: Aboveground Slow [Type]
</td>
<td style="text-align:right;">
7140.2
</td>
<td style="text-align:right;">
6871.6
</td>
<td style="text-align:right;">
-268.6
</td>
<td style="text-align:right;">
-3.8
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
DOM: Belowground Slow [Type]
</td>
<td style="text-align:right;">
23572.1
</td>
<td style="text-align:right;">
23457.3
</td>
<td style="text-align:right;">
-114.8
</td>
<td style="text-align:right;">
-0.5
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
DOM: Belowground Very Fast [Type]
</td>
<td style="text-align:right;">
143.3
</td>
<td style="text-align:right;">
143.5
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:right;">
0.2
</td>
</tr>
<tr>
<td style="text-align:left; padding-left:  2em;" indentlevel="1">
Total
</td>
<td style="text-align:right;">
30855.6
</td>
<td style="text-align:right;">
30472.4
</td>
<td style="text-align:right;">
-383.1
</td>
<td style="text-align:right;">
-1.2
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Note: </span>
</td>
</tr>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> The Aboveground Slow pool has been included with the IPCC Soil pool rather than the Litter pool as done in the CBM-CFS3 model.
</td>
</tr>
</tfoot>
</table>
<p>Net losses in live biomass carbon were concentrated in three western U.S. ecoregions (Sierra Nevada Mountains, Klamath Mountains, Cascades), primarily the result recent high rates wildfire. All other ecoregions in the U.S. were net sinks of live carbon (Figure <a href="results.html#fig:stockchangeeco">4.3</a>). The Middle Rockies and Northern Rockies ecoregions were large sinks of live carbon resulting primarily from regrowth following high rates of historical disturbance which occurred prior to 2001. Consequently, these regions also experienced significant net declines in litter and deadwood pools as stocks decomposed over time. Deadwood pools increased significantly in western ecoregions which have experienced several recent years of large stand-replacing wildfires. Declines in soil carbon were ubiquitous across ecoregions, although represent a relatively small portion of the overall soil pool. The largest declines were associated with near-surface soil horizons which were most vulnerable to emissions from wildfire and increasing rates of decay due to rising temperature.</p>
<div class="figure"><span id="fig:stockchangeeco"></span>
<img src="test_files/figure-html/stockchangeeco-1.png" alt="Net change in carbon pools by ecoegion for the period 2001-2020. " width="768" />
<p class="caption">
Figure 4.3: Net change in carbon pools by ecoegion for the period 2001-2020.
</p>
</div>
</div>
<div id="carbon-fluxes" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Carbon fluxes</h2>
<p>In addition to the reference simulation, which included the combined effects of LULC/disturbance and weather and climate, we ran three additional simulations to assess the sensitivity of major controlling factors on ecosystem carbon dynamics. The additional simulations included a) a scenario where only weather and climate effects were included (“Climate Only”), b) a scenario were only LULC and disturbances were included (“LULC-D Only”), and c) a simulation where neither LULC or climate was included (“No Effects”). Figure <a href="results.html#fig:flowresults">4.4</a> shows the estimated net primary productivity (NPP), heterotrophic respiration (Rh), net ecosystem productivity (NEP) and net biome productivity (NBP) over time for each of the four simulations.</p>
<p>The size of the net sink varied considerably from year-to-year, ranging from -19 Tg C yr<sup>-1</sup> (source) to 247 Tg C yr<sup>-1</sup> (sink). Climate was the primary driver of inter-annual variability in the size of the forest sink. When climate was not included in simulations, the size of the net sink ranged from 8 to 196 Tg C yr<sup>-1</sup> and showed a declining trend over time due to the absence of increased productivity from recent climate conditions. Land use, land-use change, and disturbances were the primary controlling processes effecting the magnitude of the net carbon sink. When LULC was excluded, the forest carbon sink was 49% higher (mean of 271 Tg C yr<sup>-1</sup>) than simulations where LULC was included.</p>
<p>Net primary productivity (NPP) of U.S. forests averaged 1,238 Tg C yr<sup>-1</sup>. Incorporating the effects of LULC and disturbances reduced total NPP by 49 Tg C yr<sup>-1</sup>. Incorporating the effects of climate resulted in an increase in NPP of 9 Tg C yr<sup>-1</sup> compared to the LULC only simulation. These results suggest that LULC and disturbance have a negative impact on NPP while climate variability and change have resulted in increased productivity of U.S. forests. Heterotrophic respiration (Rh) increased under all simulations resulting from increases in productivity, climate warming, and the effects of land use history. Net ecosystem productivity (NEP) (the difference between NPP and Rh) is the net carbon sink before LULC and disturbances are accounted for. Under the reference scenario (“LULC-D+Climate”), we estimated mean annual NEP at 218 Tg C yr<sup>-1</sup>. With a mean annual NBP rate of 125 Tg C yr<sup>-1</sup> we attribute 93 Tg C yr<sup>-1</sup> to ecosystem removals resulting from LULC and disturbances.</p>
<div class="figure"><span id="fig:flowresults"></span>
<img src="test_files/figure-html/flowresults-1.png" alt="Net fluxes of carbon in conterminous U.S. forests for the period 2002-2020. Need to delete this part..." width="768" />
<p class="caption">
Figure 4.4: Net fluxes of carbon in conterminous U.S. forests for the period 2002-2020. Need to delete this part…
</p>
</div>
</div>
<div id="effects-of-lulc-and-disturbance" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Effects of LULC and disturbance</h2>
<p>Table <a href="results.html#tab:lulcfluxtable">4.2</a> shows the emission, harvest, and mortality fluxes for the LULC and disturbances transitions considered in this study. The cumulative loss of carbon sequestration was primarily from the transfer of carbon to harvested wood products (64 Tg C yr<sup>-1</sup>) with clearcut harvest accounting for more than 90% of the carbon removal from ecosystems. Harvest activities also resulted in a similar amount of carbon transferred from live to DOM pools. Our estimate was considerably lower than other studies, including those from <span class="citation"><a href="supplemental-material.html#ref-liu2020critical" role="doc-biblioref">J. Liu et al.</a> (<a href="supplemental-material.html#ref-liu2020critical" role="doc-biblioref">2020</a>)</span> (133 Tg C yr<sup>-1</sup>), <span class="citation"><a href="supplemental-material.html#ref-williams2012carbon" role="doc-biblioref">Williams et al.</a> (<a href="supplemental-material.html#ref-williams2012carbon" role="doc-biblioref">2012</a>)</span> (107 Tg C yr<sup>-1</sup>), and <span class="citation"><a href="supplemental-material.html#ref-usgcrp2018soccr2" role="doc-biblioref">USGCRP</a> (<a href="supplemental-material.html#ref-usgcrp2018soccr2" role="doc-biblioref">2018</a>)</span> (113 Tg C yr<sup>-1</sup>), likely the result of a large underestimation of forest thinning rates which are not well detected in the Landfire disturbance data. <span class="citation"><a href="supplemental-material.html#ref-liu1804baseline" role="doc-biblioref">S. Liu et al.</a> (<a href="supplemental-material.html#ref-liu1804baseline" role="doc-biblioref">2014</a>)</span> found a similar finding, where remote sensing based approaches tend to underestimate forest havest carbon removals relative to methods which rely on forest inventory alone.</p>
<p>Ecosystem carbon losses from combustion averaged 21 Tg C yr<sup>-1</sup>, with wildfire accounting for 76% of all LULC and disturbance related emissions; emissions from urbanization and agricultural expansion accounted for 19% and 5%, respectfully. Emissions from wildfire were highly variable from year-to-year. However, the three highest fire emission years all occurred since 2017. In 2020, wildfire burned ~3.7 million hectares, primarily in California and Oregon, an amount 231% greater than the historical average. Emissions were estimated to be 73.51 Tg C (269.79 Tg CO<sub>2</sub>), which were more then three times the historical average.</p>
<p>In addition to ecosystem carbon removals, LULC and disturbances resulted in the transfer of an additional 93 Tg C yr<sup>-1</sup> from live to DOM pools which will contribute to future years reductions in the carbon sink through their decay and decomposition. This future flux could be accelerated by continued increases in the turnover rate of DOM resulting from climate warming.</p>
<table class=" lightable-paper" style="font-size: 12px; font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:lulcfluxtable">Table 4.2: </span>Average annual Fluxes of carbon resulting from land use, land-use change, and disturbances for the period 2001-2020. Emissions refer to the direct combustion of carbon to the atmosphere as either carbon monoxide, methane, or carbon dioxide. All emissions are shown in units of carbon. Harvest refers to the transfer of carbon out of the ecosystem to harvested wood products. Mortality is the transfer of live carbon to DOM pools. Transfer refers to the transfer of carbon from one DOM pool to another. Units are in Tg C yr.
</caption>
<thead>
<tr>
<th style="text-align:left;">
TransitionGroupID
</th>
<th style="text-align:left;">
Transition Type
</th>
<th style="text-align:right;">
Emission
</th>
<th style="text-align:right;">
Harvest
</th>
<th style="text-align:right;">
Mortality
</th>
<th style="text-align:right;">
Transfer
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: top !important;" rowspan="3">
Ag Expansion
</td>
<td style="text-align:left;">
Ag Expansion: Cropland
</td>
<td style="text-align:right;">
0.58
</td>
<td style="text-align:right;">
0.44
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Ag Expansion: Pasture
</td>
<td style="text-align:right;">
0.56
</td>
<td style="text-align:right;">
0.49
</td>
<td style="text-align:right;">
0.25
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
1.14
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
0.51
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: top !important;" rowspan="5">
Urbanization
</td>
<td style="text-align:left;">
Urbanization: High
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Urbanization: Medium
</td>
<td style="text-align:right;">
0.73
</td>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Urbanization: Low
</td>
<td style="text-align:right;">
1.19
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Urbanization: Open
</td>
<td style="text-align:right;">
1.74
</td>
<td style="text-align:right;">
0.66
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
3.89
</td>
<td style="text-align:right;">
1.46
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: top !important;" rowspan="3">
Forest Harvest
</td>
<td style="text-align:left;">
Forest Harvest: Forest Clearcut
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
59.41
</td>
<td style="text-align:right;">
57.31
</td>
<td style="text-align:right;">
6.95
</td>
</tr>
<tr>
<td style="text-align:left;">
Forest Harvest: Forest Selection
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
2.19
</td>
<td style="text-align:right;">
2.15
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
61.60
</td>
<td style="text-align:right;">
59.46
</td>
<td style="text-align:right;">
6.95
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: top !important;" rowspan="4">
Fire
</td>
<td style="text-align:left;">
Fire: High Severity
</td>
<td style="text-align:right;">
5.60
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
8.22
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Fire: Medium Severity
</td>
<td style="text-align:right;">
3.96
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
5.68
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Fire: Low Severity
</td>
<td style="text-align:right;">
6.34
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
6.72
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
15.90
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
20.62
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: top !important;" rowspan="4">
Insect
</td>
<td style="text-align:left;">
Insect: High Severity
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
6.05
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Insect: Medium Severity
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
4.96
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Insect: Low Severity
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
6.25
</td>
<td style="text-align:right;">
—
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
—
</td>
<td style="text-align:right;">
17.26
</td>
<td style="text-align:right;">
—
</td>
</tr>
</tbody>
</table>
</div>
<div id="projections-of-carbon-change" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Projections of carbon change</h2>
<p>We projected future changes in forest carbon dynamics for the western U.S. based on downscaled climate data for the RCP 4.5 radiative forcing scenario. We selected the CanESM2 and HADGEM2-ES365 downscaled climate futures to represent “hot-dry” and “warm-wet” futures, respectively <span class="citation">(<a href="supplemental-material.html#ref-bedsworth2017" role="doc-biblioref">Bedsworth et al. 2017</a>)</span>. Climate data from the Coupled Model Inter-comparison Project (CMIP5) were downscaled using the Multivariate Adaptive Constructed Analogs (MACA) (<span class="citation"><a href="supplemental-material.html#ref-abatzoglou2012comparison" role="doc-biblioref">Abatzoglou and Brown</a> (<a href="supplemental-material.html#ref-abatzoglou2012comparison" role="doc-biblioref">2012</a>)</span>). Downscaled climate data were used to produce a time series of spatial flow multipliers used to scale annual vegetation growth and the decay and decomposition of DOM at the pixel level. Future LULC and disturbances were sampled, with replacement, from historical rates of change following methods described in <span class="citation"><a href="supplemental-material.html#ref-sleeter2019effects" role="doc-biblioref">Benjamin M. Sleeter et al.</a> (<a href="supplemental-material.html#ref-sleeter2019effects" role="doc-biblioref">2019</a>)</span>. Additional details are described in the methods section.</p>
<p><img src="test_files/figure-html/fluxprojectionplot-1.png" width="768" /></p>
<p><a href="#fig:fluxprojectionplot"><strong>??</strong></a> shows the total ecosystem carbon storage for the historical and alternative climate futures for each of the 11 western states included in the simulation. Over the historical period, the western U.S. was a small net sink of carbon, with NBP estimated at 4.8 Tg C yr<sup>-1</sup>. Under the warm-wet model, the size of the sink was projected to increase slightly to 6.6Tg C yr<sup>-1</sup>. However, under the “hot-dry” model, western forested ecosystems were projected to transition to a net source of carbon to the atmosphere at an annualized rate of -0.9Tg C yr<sup>-1</sup>. However, the total annualized sink estimate masks considerable variability in both time and space, with some states projected as net sinks while others were projected to be a net source. Differences in climate scenarios are also evident. In most states, the “warm-wet” future results in greater net sequestration relative to the “hot-dry” scenario. However, the differences between scenarios can be more or less pronounced depending on geographic variability.</p>
</div>
<div id="carbon-emissions-from-wildfire-in-california" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> Carbon emissions from wildfire in California</h2>
<pre><code>## [1] 75</code></pre>
<p><img src="test_files/figure-html/calfiredata-1.png" width="672" /></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="discussion.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/00_lucas-cbm-methods-initial-draft-v0.1.rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["test.pdf", "test.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
